### ISSUE TITLE
Compatibility with BetterRolls

### ISSUE THREAD

**Issue by DarKDinDoN** [Kekilla0/Item-Macro#2]
Hello,

That module is awesome. No more macros the player shouldn't delete. Just click or drag and drop from the character sheet!
Would you think it's possible to make it compatible with BetterRolls? https://github.com/RedReign/FoundryVTT-BetterRolls5e

**Comment by Kekilla0** [comment]
It is and it isn't... so whatever you want to put in the macro it will execute. So that includes any better rolls macro calls. BUT just like pretty much any other thing like Item Macro, Better Rolls, or Minor Quality of Life... they each want to take control of certain aspects of the game (character sheet picture icon rollers, hot bar drop in handling, etc). So they are all fighting for the same thing and I think all doing it the same way. I haven't used Better Rolls in a while but if you want you can send me a message on discord and I might be able to work with you to see what can be done.

**Comment by davout1806** [comment]
So is this why if I have BetterRolls active, the macro runs if I activate the item from the sheet, but if I drag the item to the macro bar, the attached macro does not?

Thanks

**Comment by Kekilla0** [comment]
> So is this why if I have BetterRolls active, the macro runs if I activate the item from the sheet, but if I drag the item to the macro bar, the attached macro does not?
> 
> Thanks

so both better rolls and item macro are trying to hijack those functions, so if you have both enabled, better rolls might win or itemMacro might. They are written very similarly (its like the item macro author kinda copied better rolls)
